#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

tmp_dir="$(mktemp -d)"
output_file="$(mktemp)"
trap 'rm -rf "$tmp_dir" "$output_file"' EXIT

crate_version="$(
  cargo metadata --no-deps --format-version=1 |
    jq -r '.packages[] | select(.name == "logbrew-cli").version'
)"

if [[ -z "$crate_version" || "$crate_version" == "null" ]]; then
  printf 'could not read logbrew-cli version from Cargo metadata\n' >&2
  exit 1
fi

artifact_fixture="$tmp_dir/artifacts"
source_fixture="$tmp_dir/source"
source_root="$source_fixture/logbrew-cli-${crate_version}"

write_source_fixture() {
  local version="${1:-$crate_version}"

  rm -rf "$artifact_fixture" "$source_fixture"
  mkdir -p "$artifact_fixture" "$source_root/src"

  cat >"$source_root/Cargo.toml" <<TOML
[package]
name = "logbrew-cli"
version = "${version}"
edition = "2024"
license = "MIT"

[[bin]]
name = "logbrew"
path = "src/main.rs"
TOML

  cat >"$source_root/Cargo.lock" <<LOCK
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "logbrew-cli"
version = "${version}"
LOCK

  cat >"$source_root/src/main.rs" <<'RS'
fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args == ["--version"] || args == ["version"] {
        println!("logbrew {}", env!("CARGO_PKG_VERSION"));
        return;
    }

    if args == ["--json", "version"] {
        println!(
            r#"{{"arch":"test","binary":"source","name":"logbrew","ok":true,"os":"test","version":"{}"}}"#,
            env!("CARGO_PKG_VERSION"),
        );
        return;
    }

    eprintln!("unexpected logbrew args: {}", args.join(" "));
    std::process::exit(1);
}
RS

  printf 'readme\n' >"$source_root/README.md"
  printf 'license\n' >"$source_root/LICENSE"

  (cd "$source_fixture" && tar -czf "$artifact_fixture/source.tar.gz" "logbrew-cli-${crate_version}")
  if command -v shasum >/dev/null 2>&1; then
    (cd "$artifact_fixture" && shasum -a 256 source.tar.gz | awk '{print $1 " *source.tar.gz"}' >source.tar.gz.sha256)
  else
    (cd "$artifact_fixture" && sha256sum source.tar.gz >source.tar.gz.sha256)
  fi
}

run_smoke() {
  LOGBREW_DIST_SOURCE_ARTIFACTS_DIR="$artifact_fixture" \
    bash scripts/test-dist-source-artifact-smoke.sh "v${crate_version}" >"$output_file" 2>&1
}

expect_failure() {
  local expected_line="$1"

  : >"$output_file"
  if run_smoke; then
    printf 'expected dist source artifact smoke to fail\n' >&2
    exit 1
  fi

  if ! grep -Fq "$expected_line" "$output_file"; then
    printf 'expected dist source artifact output to contain: %s\n' "$expected_line" >&2
    printf 'actual output:\n' >&2
    cat "$output_file" >&2
    exit 1
  fi
}

write_source_fixture
: >"$output_file"
if ! run_smoke; then
  printf 'expected dist source artifact fixture to pass\n' >&2
  printf 'actual output:\n' >&2
  cat "$output_file" >&2
  exit 1
fi

if ! grep -Fq "Dist source artifact smoke passed for source.tar.gz." "$output_file"; then
  printf 'expected dist source artifact success output\n' >&2
  printf 'actual output:\n' >&2
  cat "$output_file" >&2
  exit 1
fi

write_source_fixture
rm "$artifact_fixture/source.tar.gz"
expect_failure "Dist source artifact smoke failed: missing generated artifact source.tar.gz"

write_source_fixture
rm "$artifact_fixture/source.tar.gz.sha256"
expect_failure "Dist source artifact smoke failed: missing generated artifact source.tar.gz.sha256"

write_source_fixture "0.0.0"
expect_failure "Dist source artifact smoke failed: source Cargo metadata must report version ${crate_version}"

printf 'Dist source artifact smoke self-test passed.\n'
